{"uuid": "e109c9e1-7348-480c-bab9-ffc1f6000a4a", "children": ["9e07ff4e-0a23-4b39-a903-08597f04a1e5", "f149fb47-21c5-4f33-9184-ca1167375554", "cb2602db-907e-4d8e-be67-3b7a03e2b9b3"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e9ffd00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/tests/conftest.py\", line 10, in beforeClass\n    driver = objectDriver.getDriver()\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/base/Driver.py\", line 15, in getDriver\n    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', caps)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 433, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/jarvis/Documents/training/online/appium/appiumPythonFramework/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1658613174627, "stop": 1658613174638}], "start": 1658613174627, "stop": 1658613175160}